### ISSUE TITLE
urdf parser not robust 

### ISSUE THREAD

**Issue by Jackiezhou233** [openrr/urdf-rs#105]
I fail to load one urdf file 
"let urdf_robot = urdf_rs::read_file(path).ok()?;"
and get  Error: Urdf(UrdfError(Other("invalid float literal")))
The reason is simply because there is one extra space before a float:
![image](https://github.com/user-attachments/assets/b7994d9f-5363-405d-ab0f-527499f81d51)
maybe add a .trim() before transfer string into float
I think this case should be fixed

**Comment by taiki-e** [comment]
This is actually handled on the XML parser side, so I think it is a problem on their end.

However, the XML parser we are currently using has a number of other bugs (https://github.com/openrr/urdf-rs/issues/96) and we are considering switching to another parser.

Using https://github.com/openrr/urdf-rs/pull/98 switching to another parser or the old version of urdf-rs (e.g., 0.6) that used a different parser may handles this as you expect.

**Comment by taiki-e** [comment]
Fixed in 0.9.0 (#109).
