### ISSUE TITLE
Add support for passing arguments to xacro files

### ISSUE THREAD

**Issue by JafarAbdi** [openrr/urdf-rs#60]
Currently, there's no way to load a xacro file that expects command line arguments. 

[convert_xacro_to_urdf](https://github.com/openrr/urdf-rs/blob/main/src/utils.rs#L10-L30) expects only a filename, changing the signature is an API breaking change, do you have a better solution or are you ok with breaking the API?

I'm more than happy to implement it!

**Comment by OTL** [comment]
Hi,

I do not like to change API, but you can add new API like *_with_args.
Does it works in your case?

2023年2月12日(日) 6:45 Jafar ***@***.***>:
